import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
//import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {
          //<NextTopLoader color="#161616" />
        }
        <main className="container mx-auto max-w-2xl mt-4 space-y-4">
          {children}
        </main>
      </body>
    </html>
  );
}
